#!/usr/bin/env sh
echo setup-shells

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

# Interesting readings:
# https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell/46856#46856
function setup_shell () {
  SHELL_CURRENT=`echo $SHELL`
  SHELL_NEW=/usr/bin/fish
  
  echo -e "Current SHELL is $SHELL_CURRENT"
  
  if [[ ! $SHELL_CURRENT =~ fish ]]; then
    # https://blog.liang2.tw/posts/2017/01/without-chsh/
    if "$SHELL_NEW" -c 'echo "Test fish running" >/dev/null' ; then
      chsh -s $SHELL_NEW maxdevjs
      echo -e "$SHELL_NEW is the new  default SHELL"
    else
      echo "Failed to launch fish shell. Go check its installation!"
      echo "Fall back to default shell $SHELL ..."
    fi
  fi
  REPOS=(fish)
  repos "${REPOS[@]}"
  ~/.config/fish/setup/setup
}

setup_shell
