#!/usr/bin/env sh

# look at this: it sets things up
. ./setup-utilities
. ./setup-system-packages

# System

. ./setup-shells
. ./setup-direnv
. ./setup-fonts
. ./setup-guix
. ./setup-nix
. ./setup-ssh
. ./setup-flatpak
. ./setup-bspwm
. ./setup-i3
. ./setup-3rd-party # TODO: check this
. ./setup-samba

# Dev

. ./setup-deno
. ./setup-dev-tools
. ./setup-docker
. ./setup-dlang
. ./setup-go
. ./setup-nvim

#. ./setup-vnc
#. ./setup-gnome
#. ./setup-yadm

#install_3rd_party "${PACKAGES_3RD_PARTY[@]}"


# https://averagelinuxuser.com/after-installing-solus/

