#!/usr/bin/env sh
echo setup-ssh

function setup_ssh () {
  if [[ ! `systemctl status sshd.service | grep Active | cut -d':' -f2` == *"active (running)"* ]]; then
    sudo systemctl enable sshd && systemctl start sshd
  fi
}

setup_ssh
