#!/usr/bin/env sh
echo setup-utilities

# https://www.tutorialspoint.com/unix/unix-basic-operators.htm

BIN_DIR=$HOME/.local/bin
LIST_INSTALLED=`eopkg list-installed | cut -d' ' -f1`

git_remote_url_reachable() {
  git ls-remote "$1" CHECK_GIT_REMOTE_URL_REACHABILITY &>/dev/null
}

exists() { type -t "$1" > /dev/null 2>&1; }

not_exists_dir() { 
  [ ! -d $1 ]
}

function repos() {
  list=("$@")

  for repo in "${list[@]}"; do
    cd $XDG_CONFIG_HOME

    if not_exists_dir $XDG_CONFIG_HOME/$repo
    then
      URL=https://github.com/maxdevjs/dotfiles-${repo}-config
      
      # https://superuser.com/a/1415376
      if git_remote_url_reachable "$URL"; then
         git clone $URL ${repo}
      else
        echo -e "\n\tApparently ${URL} does not exists (or it is not reachable at the moment)\n\tRemember to check it manually."
        echo
      fi
    else
      cd $XDG_CONFIG_HOME/$repo
      echo -e "\t$PWD\n\tChecking if $repo is up-to-date, otherwise pulling updates."
      git pull
      echo
    fi
  done
}

# https://stackoverflow.com/a/37939589
function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

if [ ! -d "$BIN_DIR" ]; then
  mkdir -p $BIN_DIR
fi

cp ./.local/share/applications/restart-budgie.desktop ~/.local/share/applications/
