#!/usr/bin/env sh
echo setup-i3

. ./setup-utilities

function setup_i3 () {
  # https://getsol.us/articles/software/desktop-environments/en/
  if ! exists i3; then
    sudo eopkg install dunst i3 nitrogen polybar rofi
  fi
  
  REPOS=(dunst i3 polybar)
  repos "${REPOS[@]}"
   
}

setup_i3
