#!/usr/bin/env sh
echo setup-nvim

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

setup_nvim () {
  install_packages $@
  
  # TODO: check when backup config
  
  #mv ~/.config/nvim ~/.config/nvimbackup
  # Currently testing AstroNvim
  single_repo https://github.com/AstroNvim/AstroNvim nvim
  single_repo https://github.com/maxdevjs/dotfiles-astronvim-config astronvim
  
  # Initialize AstroNvim
  #nvim  --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  # setup LSP install
  #
}

PACKAGES_NVIM=(neovim)

setup_nvim "${PACKAGES_NVIM[@]}"

