#!/usr/bin/env sh
echo setup-direnv

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

function setup_direnv () {
  # https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
  REMOTE_VERSION=`curl -s https://api.github.com/repos/direnv/direnv/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c2-`

  if ! exists $BIN_DIR/direnv; then
    curl -sfL https://direnv.net/install.sh | bash
  else
    INSTALLED_VERSION=`direnv --version`
    
    if [ $(version $INSTALLED_VERSION) -lt $(version $REMOTE_VERSION) ]; then
      echo -e "Updating direnv to ${REMOTE_VERSION}"
      curl -sfL https://direnv.net/install.sh | bash
    else
      echo "Installed version (${INSTALLED_VERSION}) is up to date (remote is ${REMOTE_VERSION})"
    fi
  fi
}

setup_direnv
