#!/usr/bin/env sh
echo setup-go

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

function setup_go () {
  
  if ! exists go; then
    install_packages $@
  fi
  
  # Afterwards, the update process is up to the system package manager
}

PACKAGES_GO=(golang)

setup_go "${PACKAGES_GO[@]}"

